image: microsoft/dotnet:latest

stages:
  - build
  - test

variables:
  ELASTIC_HOST: elasticsearch
  ELASTIC_PORT: "9200"
  ES_JAVA_OPTS: "-Xms512m -Xmx512m"
  ELASTICSEARCH_URL: "http://elasticsearch:9200"

build:
  stage: build
  script:
    - cd ElasticsearchSupplyCollector
    - dotnet build

test:
  stage: test
  services:
    - name: docker.elastic.co/elasticsearch/elasticsearch:6.3.2
      alias: elasticsearch
      command: [ "bin/elasticsearch", "-Ediscovery.type=single-node" ]
    - name: docker.elastic.co/kibana/kibana:6.3.2
      alias: kibana
  script:
    - cd ElasticsearchSupplyCollector
    - dotnet build
    - cd ElasticsearchDataLoader
    - dotnet run
    - cd ..
    - dotnet test
