image: s2shape/s2shape-test-harness:latest

stages:
  - build
  - test

variables:
  ELASTIC_HOST: elasticsearch
  ELASTIC_PORT: "9200"
  ES_JAVA_OPTS: "-Xms512m -Xmx512m"
  ELASTICSEARCH_URL: "http://elasticsearch:9200"

before_script:
  - dotnet restore -s https://www.myget.org/F/s2/ -s https://api.nuget.org/v3/index.json

build:
  stage: build
  script:
    - cd ElasticsearchSupplyCollector
    - dotnet build

test:
  stage: test
  services:
    - name: docker.elastic.co/elasticsearch/elasticsearch:6.3.2
      alias: elasticsearch
      command: [ "bin/elasticsearch", "-Ediscovery.type=single-node" ]
    - name: docker.elastic.co/kibana/kibana:6.3.2
      alias: kibana
  script:
    - ROOT_PROJECT_PATH=$(pwd)
    - dotnet build
    - dotnet publish
    - cd $ROOT_PROJECT_PATH/ElasticsearchSupplyCollectorLoader/bin/Debug/netcoreapp2.2/publish
    - cp -f /SupplyCollectorDataLoader/SupplyCollectorDataLoader/bin/Debug/netcoreapp2.2/SupplyCollectorDataLoader.runtimeconfig.json .
    - dotnet SupplyCollectorDataLoader.dll -init ElasticsearchSupplyCollector http://$ELASTIC_HOST:$ELASTIC_PORT
    - dotnet SupplyCollectorDataLoader.dll -xunit ElasticsearchSupplyCollector http://$ELASTIC_HOST:$ELASTIC_PORT
    - cd $ROOT_PROJECT_PATH
    - dotnet test

load_test:
  stage: test
  services:
    - name: docker.elastic.co/elasticsearch/elasticsearch:6.3.2
      alias: elasticsearch
      command: [ "bin/elasticsearch", "-Ediscovery.type=single-node" ]

  script:
    - ROOT_PROJECT_PATH=$(pwd)
    - dotnet build
    - dotnet publish
    - cd $ROOT_PROJECT_PATH/ElasticsearchSupplyCollectorLoader/bin/Debug/netcoreapp2.2/publish
    - cp -f /SupplyCollectorDataLoader/SupplyCollectorDataLoader/bin/Debug/netcoreapp2.2/SupplyCollectorDataLoader.runtimeconfig.json .
    - dotnet SupplyCollectorDataLoader.dll -init ElasticsearchSupplyCollector http://$ELASTIC_HOST:$ELASTIC_PORT
    - dotnet SupplyCollectorDataLoader.dll -xunit ElasticsearchSupplyCollector http://$ELASTIC_HOST:$ELASTIC_PORT
    - dotnet SupplyCollectorDataLoader.dll -samples ElasticsearchSupplyCollector http://$ELASTIC_HOST:$ELASTIC_PORT testCollection Test1:int,Test2:string,Test3:bool,Test4:double,Test5 100000
    - cd $ROOT_PROJECT_PATH/ElasticsearchSupplyCollectorTests/bin/Debug/netcoreapp2.2/publish
    - SupplyCollectorTestHarness
